# Site Settings
title: whiteblog-theme
author: Victor Silva

permalink: /:title/ #/:categories/:title/

plugins:
  - jekyll-redirect-from


header_pages:
#  - _pages/about.md
#  - _pages/contact.md
#  - _pages/setup.md
  - _pages/github.md

include:
  - _pages

exclude:
  - Gemfile
  - Gemfile.lock
  - whiteblog-theme.gemspec